### PR TITLE
save changes before redirecting to the editor

### LINKED ISSUE #2493: holding pen: opening in editor should save
## Expected Behavior
If there are modifications to the HP record from the HP interface, clicking on `Open in Editor` should save the modifications.

## Current Behavior
Modifications are not saved.

## Steps to Reproduce (for bugs)

1. Open a record in the HP in `Halted` status
2. Do some modifications
3. Click on `Open in Editor`

### PR DESCRIPTION
**Pull request by Dinika**
Pressing the 'Open in Editor' button will now save the changes made in holdingpen before redirecting the user to the editor

closes inspirehep/inspire-next/issues/2493
Signed-off-by: Dinika <dinika.saxena@cern.ch>

### CODE REVIEW

File: src/inspirehep-holdingpen-js/holdingpen/holdingpen.directives.js [hunk 1]
```diff
@@ -270,6 +270,11 @@
             $window.location = url;
           },
 
+          saveAndRedirect: function(url) {
+            HoldingPenRecordService.updateRecord($scope.vm, $scope.workflowId);
```
Comment (jmartinm) [inline src/inspirehep-holdingpen-js/holdingpen/holdingpen.directives.js]: Is this call synchronous? Otherwise it should be something like `HoldingPenRecordService.updateRecord($scope.vm, $scope.workflowId).then(function(){})`

Comment (Dinika) [reply src/inspirehep-holdingpen-js/holdingpen/holdingpen.directives.js]: Updated the code
